Fixes brave_unit_tests dependency.
On MacOS:

Undefined symbols for architecture x86_64:
  "vtable for FakeSystemGeolocationPermissionsManager", referenced from:
      TestingBrowserProcessPlatformPart::TestingBrowserProcessPlatformPart() in libtest_support.a(testing_browser_process_platform_part.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/63eb7e0f2322359ca1214224c346ad02f5e0264e

commit 63eb7e0f2322359ca1214224c346ad02f5e0264e
Author: James Hollyer <jameshollyer@google.com>
Date:   Wed Feb 24 03:02:40 2021 +0000

    Don't use Core Location after update

    After an update the binary on the disc is different from the one
    in memory until restart. While in this state if Core Location is
    accessed macOS removes location permission. We are currently only
    using Core Location to check for current permission status.
    This fix consolidates the permission state manager to a single
    object that is created and owned by the BrowserProcess. This status
    is cached in that object and accessed when needed throughout the
    application.

    The CoreLocationProvider is currently behind a flag that is disabled
    by default. More work is needed to ensure that class does not access
    Core Location while in a broken signed state before that flag can be
    enabled.

    Bug: 1143807